Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "../demystify/__main__.py", line 136, in <module>
    "steps": explainer.explain_steps(),
  File "/Users/matthewmcilree/URAS/Demystify/demystify/demystify/explain.py", line 54, in explain_steps
    raise ExplainError("Puzzle has not been correctly initialised.")
demystify.explain.ExplainError: Puzzle has not been correctly initialised.
Cannot find res_00001_00001 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00001_00002 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00001_00003 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00001_00004 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00002_00001 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00002_00002 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00002_00003 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00002_00004 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00003_00001 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00003_00002 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00003_00003 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00003_00004 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00004_00001 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00004_00002 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00004_00003 in the VAR list SortedSet([]) -- should it be AUX?
Cannot find res_00004_00004 in the VAR list SortedSet([]) -- should it be AUX?
